# Generated by Django 3.2 on 2021-05-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('part time', 'part time'), ('full time', 'full time')], max_length=15)),
                ('description', models.TextField(max_length=500)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('vacancy', models.IntegerField(default=1)),
                ('salary', models.IntegerField(default=5000)),
                ('experience', models.IntegerField(default=1)),
            ],
        ),
    ]
